#! /bin/sh


#    bspwm config 
# >----------------->


# xrandr -o right &			    autostart
killall volumeicon &
sxhkd &
polybar -r &
nitrogen --restore &
xfce4-power-manager &
setxkbmap fi &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &


#			    basic settings

#bspc config border_radius                8
bspc config border_width                  3
bspc config window_gap                    18 
bspc config top_padding                   0 
bspc config bottom_padding                0 
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


#			    border colors


#bspc config normal_border_color		   "#0f0f0f"
bspc config focused_border_color	   "#a286fd"

bspc config normal_border_colo		   "#14161b"
#bspc config focused_border_color	   "#06795a"
# oranzzi bspc config focused_border_color	   "#c9753d"

bspc config active_border_color	           "#c10000"
bspc config presel_feedback_color	   "#5e81ac"
bspc config urgent_border_color 	   "#dd2727"



#			    floating window spots and sizes

bspc rule -a mplayer2 state=floating
bspc rule -a sweethome3d state=floating
bspc rule -a tint2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a VirtualBox state=floating
bspc rule -a tint2conf  state=floating
bspc rule -a gcolor3 state=floating
bspc rule -a gcolor state=floating
bspc rule -a Tilda state=floating
bspc rule -a gnome-calendar state=floating rectangle=900x900+660+25
bspc rule -a Gnome-weather state=floating 
bspc rule -a tint2conf state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Designer state=floating
bspc rule -a Nvpy state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Cpupower-gui state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Arandr state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Simplenote state=floating




#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^1'
#bspc rule -a Pcmanfm desktop='^3'


#			    panel/bar preferences

#tint2
bspc rule -a tint2 layer=below

#polybar hidden when fullscreen for vlc, youtube, mpv ...
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)


#make desktops ( 10 )
bspc monitor -d 1web 2dev 3sys 4 5 6 7virt 8term 9radio boom


#### MONITORS ####
#find out the name of your monitor with xrandr
#bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
#bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9


